# Generated by Django 6.0.6 on 2026-06-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
                (
                    "gate_number",
                    models.IntegerField(
                        choices=[(1, "Portail 1"), (2, "Portail 2"), (3, "Portail 3")]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecognizedPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("plate_text", models.CharField(blank=True, max_length=20)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("box_x", models.IntegerField(blank=True, default=0, null=True)),
                ("box_y", models.IntegerField(blank=True, default=0, null=True)),
                ("box_w", models.IntegerField(blank=True, default=0, null=True)),
                ("box_h", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "vehicle_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Tourisme"),
                            (2, "Camion"),
                            (3, "Camionnette"),
                            (4, "Autocar"),
                            (5, "Tracteur routier"),
                            (6, "Autre tracteur"),
                            (7, "Spécial"),
                            (8, "Remorque"),
                            (9, "Moto"),
                        ],
                        null=True,
                    ),
                ),
                ("gate", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Entrée"), ("out", "Sortie")],
                        default="in",
                        max_length=10,
                    ),
                ),
                (
                    "entry_method",
                    models.CharField(
                        choices=[("auto", "Automatique"), ("manual", "Manuel")],
                        default="auto",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_agent", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
