# Generated by Django 6.0.6 on 2026-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognizedplate",
            name="annee",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognizedplate",
            name="numero_enregistrement",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognizedplate",
            name="wilaya",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
