# Generated by Django 6.0.6 on 2026-06-09 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_recognizedplate_annee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_threshold", models.FloatField(default=0.4)),
                ("history_retention_days", models.PositiveIntegerField(default=30)),
                ("capture_interval_seconds", models.PositiveIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre administration",
                "verbose_name_plural": "Paramètres administration",
            },
        ),
        migrations.AlterModelOptions(
            name="recognizedplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="recognizedplate",
            name="duration_minutes",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognizedplate",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entered_plates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recognizedplate",
            name="exit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assigned_gate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="camera",
            name="gate_number",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Portail 1"), (2, "Portail 2"), (3, "Portail 3")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="recognizedplate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
